#!/bin/zsh

alias ls='ls -Gh'
alias ll='ls -l'
alias la='ls -lA'
alias lsd='ls -d */' #list only dirs
alias l='la'
alias grep='grep --color'
alias Preview='/Applications/Preview.app/Contents/MacOS/Preview'
alias wget='curl -O'
alias ql='qlmanage -p'
alias pag="ps aux | grep "

# Apache / mysql
alias apachestart='sudo apachectl start'
alias apachestop='sudo apachectl stop'
alias apacherestart='sudo apachectl restart'
alias mysqlstart='mysql.server start'
alias mysqlstop='mysql.server stop'
alias mysqlrestart='mysql.server restart'
alias ampup='mysqlstart | apachestart'
alias ampdown='mysqlstop | apachestop'
alias amprestart='mysqlrestart | apacherestart'
alias fixwpupdate='sudo chown -R _www'
alias fixwpuser= 'sudo chown -R g+w'

#WordPress Sites shortcuts
alias req='cd Sites/required/'
alias reqp='cd Sites/required-projects/'
alias reqf='cd Sites/required-projects/required-foundation/wordpress/wp-content/themes/'

# git
alias ga.='ga .'
alias ga='git add'
alias gb='git branch -v'
alias gba='git branch -a -v'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gco='git checkout'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gd='git diff'
alias gf='git fetch'
alias gl='git pull'
alias glg='git log --stat --max-count=5'
alias glo='git log'
alias glog='git log --graph'
alias glr='git pull --rebase'
alias gm='git merge'
alias gmf='git merge --ff-only'
alias gp='git push'
alias gr='git remote'
alias grs='git reset --hard'
alias gs='git status'
alias gsm='git submodule init'
alias gso='git show'
alias gsv='git svn'
alias gst='git config --add remote.origin.fetch "+refs/notes/*:refs/notes/*"'
alias gt='git notes --ref=jenkins show'

#mercurial
alias ha='hg add'
alias hc='hg commit'
alias hl='hg pull'
alias hp='hg push'
alias hlog='hg log'
alias hb='hg branch'
alias hs='hg status'


# subversion
alias setSvnExternals='svn propset svn:externals -F ./EXTERNALS.TXT .'
alias setSvnIgnore='svn propset svn:ignore -F ./IGNORE.TXT .'

# scm
alias ssd='scm stash dry'
alias ss='scm stash'
alias ssa='scm stash apply'
alias ssl='scm stash list'

rationalise-dot() {
if [[ $LBUFFER = *.. ]]; then
    LBUFFER+=/..
else
    LBUFFER+=.
fi
}
zle -N rationalise-dot
bindkey . rationalise-dot

alias ..='cd ..'
alias ../..='cd ../..'
alias ../../..='cd ../../..'
alias ../../../..='cd ../../../..'
alias ../../../../..='cd ../../../../..'
alias ../../../../../..='cd ../../../../../..'
alias ../../../../../../..='cd ../../../../../../..'
alias ../../../../../../../..='cd ../../../../../../../..'
alias ../../../../../../../../..='cd ../../../../../../../../..'
alias ../../../../../../../../../..='cd ../../../../../../../../../..'
alias ../../../../../../../../../../..='cd ../../../../../../../../../../..'
alias ../../../../../../../../../../../..='cd ../../../../../../../../../../../..'
alias ../../../../../../../../../../../../..='cd ../../../../../../../../../../../../..'


# Mac Application aliases
alias firefox='open -a firefox'
alias preview='open -a Preview'
alias mail='open -a AirMail'
alias skype='open -a Skype'
alias adium='open -a Adium'
alias ical='open -a Calendar'
alias finder='open -a Finder'

#Extensions
alias -s pdf=preview
alias -s odt=preview
alias -s doc=preview
alias -s docx=preview
alias -s rtf=preview
alias -s ods=preview
alias -s xls=preview
alias -s xlsx=preview
alias -s odp=preview
alias -s ppt=preview
alias -s pptx=preview

alias -s htm=firefox
alias -s html=firefox
alias -s xml=firefox

alias -s png=preview
alias -s jpg=preview
alias -s gif=preview

alias -s php=php
